trigger:
  - main
pool: 
  name: "Infra-Runners-pool"
  demands:
  - agent.name -equals office

steps:
- powershell: |
    $env:Path = "C:\agent\_work\_tool\terraform\1.12.2\x64;" + $env:Path
    terraform version
  displayName: 'Check Terraform Version'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)//terraform'
    backendServiceArm: 'WebAppServiceConnection'
    backendAzureRmResourceGroupName: 'aks-rg'
    backendAzureRmStorageAccountName: 'aksstorrage'
    backendAzureRmContainerName: 'aks-container'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'