trigger:
  - main
pool: 
  name: "Infra-Runners-pool"
  demands:
  - agent.name -equals office

steps:


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)//terraform'
    backendServiceArm: 'WebAppServiceConnection'
    backendAzureRmResourceGroupName: 'aks-rg'
    backendAzureRmStorageAccountName: 'aksstorrage'
    backendAzureRmContainerName: 'aks-container'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'