trigger:
  branches:
    include:
      - main

pool: 
  name: "Infra-Runners-pool"
  demands:
    - agent.name -equals office

stages:

  # Stage 1: Terraform Install
  - stage: TerraformInstall
    displayName: 'Terraform Installation'
    jobs:
      - job: TerraformInstallJob
        displayName: 'Install Terraform'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'custom'
              workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
              outputTo: 'console'
              customCommand: 'fmt'
              environmentServiceNameAzureRM: 'WebAppServiceConnection'
 