trigger:
  branches:
    include:
      - main

pool: 
  name: "Infra-Runners-pool"
  demands:
    - agent.name -equals office
steps:
  - script: |
      where terraform
      terraform -version
    displayName: 'Check Terraform Installation in Agent'
