trigger:
  - main

pool:
  name: Infra-Runners-pool
  demands:
    - agent.name -equals DESKTOP-K83M3GM

stages:
  - stage: terraformInstall
    displayName: Terraform Insatllation 
    jobs:
      - job: InatallingJobb
        displayName: Terraform Installing
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

  - stage: terraformInitStage
    displayName: Terraform Init
    jobs:
      - job: terraformInitJob
        displayName: Terraform Init 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
            backendServiceArm: 'WebAppServiceConnection'
            backendAzureRmResourceGroupName: 'aks-rg'
            backendAzureRmStorageAccountName: 'aksstorrage'
            backendAzureRmContainerName: 'aks-container'
            backendAzureRmKey: 'terraform.tfstate'

  - stage: TerraformFMTStage
    displayName: Terrafom FMT
    jobs:
      - job: terraformfmtJob
        displayName: Terraform FMT
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
            commandOptions: 'fmt'
            outputTo: 'console'
  
  - stage: TerraformPlanstage
    displayName: Terraform Plan
    jobs:
      - job: terraformPlanJob
        displayName: Terraform Plan
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
            environmentServiceNameAzureRM: 'WebAppServiceConnection'