trigger:
  - main
pool: 
  name: "Infra-Runners-pool"
  demands:
  - agent.name -equals DESKTOP-K83M3GM

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infraRepo'
    backendServiceArm: 'WebAppServiceConnection'
    backendAzureRmResourceGroupName: 'aks-rg'
    backendAzureRmStorageAccountName: 'aksstorrage'
    backendAzureRmContainerName: 'aks-container'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'