trigger:
 branches:
   include:
     - main
pool: 
  name: "Infra-Runners-pool"
  demands:
    - agent.name -equals DESKTOP-K83M3GM

stages:
    - stage: terraformInatallation
      jobs:
          - job: terraformInatallaionJob
            displayName: terraform Inatallation
            steps:
            - task: TerraformInstaller@1
              inputs:
                terraformVersion: 'latest'

            - task: TerraformTask@5
              inputs:
                provider: 'azurerm'
                command: 'custom'
                workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
                outputTo: 'console'
                customCommand: 'fmt'
                environmentServiceNameAzureRM: 'WebAppServiceConnection'

    - stage: terraformInit
      jobs:
          - job: terraforminitJob
            displayName: Terraform Init
            steps:
            - task: TerraformTask@5
              inputs:
                provider: 'azurerm'
                command: 'init'
                workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
                backendServiceArm: 'WebAppServiceConnection'
                backendAzureRmResourceGroupName: 'aks-rg'
                backendAzureRmStorageAccountName: 'modules'
                backendAzureRmContainerName: 'aks-container'
                backendAzureRmKey: 'terraform.tfstate'