trigger:
  branches:
    include:
      - main

pool: 
  name: "Infra-Runners-pool"
  demands:
    - agent.name -equals office

stages:

  # Stage 1: Terraform Install
  - stage: TerraformInstall
    displayName: 'Terraform Installation'
    jobs:
      - job: TerraformInstallJob
        displayName: 'Install Terraform'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

  # Stage 2: Terraform Format (fmt)
  - stage: TerraformFmt
    displayName: 'Terraform Format Check'
    dependsOn: TerraformInstall
    jobs:
      - job: TerraformfmtJob
        displayName: 'Run terraform fmt'
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'custom'
              workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
              customCommand: 'fmt'
              outputTo: 'console'
              environmentServiceNameAzureRM: 'WebAppServiceConnection'

  # Stage 3: Terraform Init
  - stage: TerraformInit
    displayName: 'Terraform Init'
    dependsOn: TerraformFmt
    jobs:
      - job: TerraformInitJob
        displayName: 'Terraform Init Backend'
        
        steps:

        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
            backendServiceArm: 'WebAppServiceConnection'
            backendAzureRmResourceGroupName: 'aks-rg'
            backendAzureRmStorageAccountName: 'aksstorrage'
            backendAzureRmContainerName: 'aks-container'
            backendAzureRmKey: 'terraform.tfstate'
# Terraform Plan 
               
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
            environmentServiceNameAzureRM: 'WebAppServiceConnection'

        
