trigger:
  - main
pool: 
  name: "Infra-Runners-pool"
  demands:
  - agent.name -equals kmaster

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install unzip -y
      Install unzip

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infraRepo'
    backendServiceArm: 'WebAppServiceConnection'
    backendAzureRmResourceGroupName: 'aks-rg'
    backendAzureRmStorageAccountName: 'aksstorrage'
    backendAzureRmContainerName: 'aks-container'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/infraRepo'
    environmentServiceNameAzureRM: 'WebAppServiceConnection'



