trigger:
  branches:
    include:
      - main

pool: 
  name: "Infra-Runners-pool"
  demands:
    - agent.name -equals office

stages:

  # Stage 1: Terraform Install
  - stage: TerraformInstall
    displayName: 'Terraform Installation'
    jobs:
      - job: TerraformInstallJob
        displayName: 'Install Terraform'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'custom'
              workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
              outputTo: 'console'
              customCommand: 'fmt'
              environmentServiceNameAzureRM: 'WebAppServiceConnection'
          
  - stage: terraformInstallationStage
    displayName: Terraform Inastallation Stage
    jobs:
      - job: terraformInatllationJob
        displayName: terraform Installation Job
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
            backendServiceArm: 'WebAppServiceConnection'
            backendAzureRmResourceGroupName: 'aks-rg'
            backendAzureRmStorageAccountName: 'aksstorrage'
            backendAzureRmContainerName: 'aks-container'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
            environmentServiceNameAzureRM: 'WebAppServiceConnection'
  - stage: 
    jobs:
      - job: terraformApply
        displayName: terraformApply
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'WebAppServiceConnection'


 