trigger:
  - main

pool:
  name: Infra-Runners-pool
  demands:
    - agent.name -equals office

steps:
  - task: TerraformInstaller@1
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: '1.12.2'

  - task: TerraformTask@5
    displayName: 'Terraform Init'
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
      backendServiceArm: 'WebAppServiceConnection'
      backendAzureRmResourceGroupName: 'aks-rg'
      backendAzureRmStorageAccountName: 'aksstorrage'
      backendAzureRmContainerName: 'aks-container'
      backendAzureRmKey: 'terraform.tfstate'

  - task: TerraformTask@5
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
      environmentServiceNameAzureRM: 'WebAppServiceConnection'


  - task: TerraformTask@5
    displayName: 'Terraform Plan'
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/modules'
      environmentServiceNameAzureRM: 'WebAppServiceConnection'
      commandOptions: '--auto-approve'



      


